name: nightly
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup HaxeFlixel
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.1
        run: | 
          haxelib install flixel
          haxelib install openfl
          haxelib install lime
          haxelib install flixel-addons

      - name: Build HTML5
        run: |
          haxelib run lime build html5
          mkdir public
          mv ./export/release/html5/bin/* ./public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
      
